### PR TITLE
Fixes broken tests for 0.1.7

### PR DESCRIPTION
**Pull request by Codesleuth**
It seems the build process used forgot to check that the tests were actually failing. It just so happens they they were, and it's making it very difficult to fork and extend the project.

This pull request adds a callback to `mocha.run()` that will report failures as an exit code, preventing false positives in the future.

### CODE REVIEW

**Comment by Codesleuth** [comment]
Is this project abandoned? It's been a while, and the PR's are stacking up.

**Comment by walling** [comment]
Thanks! Sorry for the [late merge](https://github.com/walling/gulp-raml2html/issues/14).

**Comment by Codesleuth** [comment]
No problem, and thank you for the merge. I'd be happy to help maintain the repo - I'll post over in the referenced issue.

Cheers!

**Comment by walling** [comment]
You're welcome.

**Pull request merged**
